name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install alsa for alsa-sys Rust package
      run: sudo apt-get install -y alsa-lib
    - name: Build
      run: cargo build --verbose
